### PR TITLE
xcoff: add resource test files

### PR DESCRIPTION
**Pull request by EsmeYi**
Add a base test file.

### CODE REVIEW

**Review by philipc — CHANGES_REQUESTED** [review]
I assume base.xcoff is an executable file? Can you also add both an object file (`base.o`), and add a script `base.sh` that contains the commands you used to generate these.

**Comment by EsmeYi** [comment]
Addressed comments.

**Comment by philipc** [comment]
Can you also add 32-bit XCOFF files?

**Comment by EsmeYi** [comment]
> Can you also add 32-bit XCOFF files?

Yes. But the 32-bit XCOFF isn't supported in https://github.com/gimli-rs/object/pull/469 now.

**Comment by EsmeYi** [comment]
Added 32-bit XCOFF files.

**Review by philipc — APPROVED** [review]
Thanks!

**Pull request merged**
